Fix java.lang.NoSuchMethodError: android.widget.Button.setBackground at eyes.blue.LamrimReaderActivity$1.onTouch(LamrimReaderActivity.java:239), it cause the Button.setBackground is only available from that API level onwards.
if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.JELLY_BEAN)
	modeSwBtn.setBackground(getResources().getDrawable(R.drawable.mode_sw_button));
else
	modeSwBtn.setBackgroundDrawable(getResources().getDrawable(R.drawable.mode_sw_button));