Try to fix the exception that cause can't initial app:
android.view.InflateException: Binary XML file line #65: Error inflating class <unknown>
java.lang.NumberFormatException: Invalid int: "4.0dip"

Reference: http://stackoverflow.com/questions/19037164/invalid-int-on-xml-android-color-file-when-launched-on-a-galaxy-tab
The property in there that was causing the problem was:
android:paddingStart="?android:attr/listPreferredItemPaddingStart"
but using android:paddingStart="5dip" also caused the same crash. Using android:paddingLeft="5dip" works fine.

Device:
Samsung Galaxy Tab2 10.1 (espresso10rf)
Samsung Galaxy Note 10.1 (p4notewifiww)