Fix [java.lang.NoSuchMethodError: android.view.Display.getSize] it cause by the Display.getSize(Point) is added on API Level 13, it not exist in older version. The function is add in r89.